apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: budget-tracker-ingressroute
  namespace: budget-tracker
spec:
  entryPoints:
    - web
  routes:
  - match: Host('budget-tracker.local.com') && PathPrefix("/")
    kind: Rule
    services:
    - name: frontend
      port: 443
      scheme: https
    tls: {}