apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: budget-tracker-ingress
  namespace: budget-tracker
  labels:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  # annotations:
  #   nginx.ingress.kubernetes.io/backend-protocol: "https"
  #   nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
spec:
  rules:
  - host: budget-tracker.local.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: frontend
            port: 
              number: 443