apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-token
  namespace: default
spec:
  encryptedData:
    password: AgBOdWDEg+avpgRZ1yz4k5HwogXSldyvKiX5cnK4ivx8HpqkxCI20C2j/sVfkezWmC1PlZteERo2eXUKlCevs3p3rsM0VED+z0jYcakSLWhBXZ3KbdmmmfgU0CKh7GH7oXfWSr5dDJVYuO7rvddpg2wDQtfIPOX+yKsBsehZXX/lPiA10GmMQRdcNbs0jkh48oAgwMym0pz3JRf/O6UTPuHNETzpyALaVd/XydUj2lIZq7u+v+Ln6C7KVS1MVRoUfZIiD2G/3+ibckutsT+I6/fQ2SThhlfKtWKLFFuQXDNsViub3QJUITo+xlZWThxL+jO6VtF93/PN4OipvSnfuy5/XG1g4gHvGiPvTDRAo75EZ3BGUThSzXsiAMmX8CgICIrNAM8jfJICrgYBHlA2SoKbuxAXjq4THKNf3GOLHnlaODAdplwa/gof0L0ue7Crt3hkNLEMmkHEsz0r1RtvND4GRi2Kq2octFoCCeJjoSGJvR8XXG/D4Q64A06z8Fm3NuR+BZlyheCGPfu+p8rXCohTi1an37RK1HiZsFd028Mv1oZhoCKwx7fZyhbLT9SItmm+0UA7UqFAGDOhmDIBAGTwPW9OOyxKNWhYx27BrOgex0WRhdDOhyc4GOOONkn+x7kVC10hp7xLZ3MDjl9bMrpl3MJ95uBUAkJ4ZVt529EDHdGRegmvNOsUXMvV7mw2cPHQCIDlEQB85tAn/w9/Un/pKN6XCIRMZDf832flgp8hfUZvrF1c3tMaQkOz
  template:
    metadata:
      name: jwt-token
      namespace: default