apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-token
  namespace: budget-tracker
spec:
  encryptedData:
    token: AgBM3JXLjOBD8oNzRYEcYHYQvdH3Ozf6DHaMe1lU/Nn9wqNQUGexCNQkK6oZpezfwGsGmPJVbQE0cxtVqEwYUyJYrkj7i9gsqa99x7tHZRm/SPSgOSbr/aJ/F5d6wXBHsU7hjIFVPyjRQDm3mi9/f9qi9N4r0Z1nZ+LqUGIXc5dbAKw4HoCgGU/snf7QYDWkJwtsQSqDOXbYyxyh3o1vO7aC7jIL71uxNqNCIbVO269zK3d/yaAcHkFqCgJV1qPSTamrN+AUf6zxR0Gdf6fld8cVZcBXNcJPEchLWUJfn+ZSvc8VsiMoGYNqpypX7l9oen3fcGOguhn7aa6Kbk1RSMn/z7J2mUvXRocYpgakzkq0pUTnTkCF6DbvHbCyDb4d7MO58b/TO8uG6HtzmwHX/iUnYiaD1UcETedU5jFO41Q6L7WCoP57AUlEodC34AY8zKG2vlHWBoovnbq7s8K4anWFg435Fuo+zAWP3kP3MuLW3RjwQbdmga0OZvrEJkFOx64aYezxIECtqOXAmKsImiaB1ddO7CZkJRG0V+LS/HPiSf9I1IzViF/0YhvxqHwNZS2ib9SNtgc1zokejY6b9ENnnk6djvjDOxKgdKJyUf5619/Y+pU3m+vr7W0Vkh6O15BpoHg2SE3W7xYNMrmKnGQZn6gqGxPa7dqUvtBB4ceAHKP+pQfGyrmA6IdjAZdOMdlxwoEVH2yxgT+YC86Phnziec/OvtXFHWjKCYaJDUBIcsI4peY5sIwkPvLu
  template:
    metadata:
      name: jwt-token
      namespace: budget-tracker

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-password
  namespace: budget-tracker
spec:
  encryptedData:
    password: AgArAvHe+92a9Cldh9p0eHh8EJqukKtYMzCavy5uD+kzMMB9w87XxW15nCmFvJygC01KSoq6uCr2TbIwJTMH2iYmbz7sQVMyX5CrqnH+tjwGLpWwY65/5YtC1HvfjGKyhcJ5Ws8N1qmeof/XMfmfrw4KfWgXF0dIWl8P3M/KuqrRYMIxP728XDx2oID8+Y27HWqi+KiH6JBQg4fY3SkvDS516DO1i3np+Ur88jMr0qtX3mog404NJcI+zxd5nspCsI2q90ZXOWPMkiqCLjY9lvgKYW5KedW8/w0H4Bkx/RLDscOOxJ13Ud6Ur7toURlgJHCYWraT7UhPx0CakL4pHRFirLvF+rPGDP10oLkyeSnAnnk8P6F8UPBiKJDcYQc4WSeHvDgsIqXcdRPxP/9BNShK5lWg/NVXMAy4Vi0yUBcN8Yviosr1Rb59zoYkm9xrDE2+S74Bz6SEYlczMmqqGeV1+S7X/q2WfF0zWgXlAqPG3QTSU/uIUwgKzwwvI1P2/eL0rM4bbmc+cLb/579jTTJOWrioYmhQm1gdnzWaF6lOxYtAO52UdduGKGrF60c+0z6jr5rUssK7YRx3+KSJJVBnj3Sk/6ygbP5PMY4Tb9eJZ8tss+yBc0oEtJoStLnQfT+Qkl6dO8pl9qC26Ratyx4FzCIqmoJlxrokoiU8Ba/TRq9TTOoBM2uu5rudD8+6gtBUXM462rDX
  template:
    metadata:
      name: db-password
      namespace: budget-tracker
      
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-password
  namespace: budget-tracker
spec:
  encryptedData:
    password: AgCer/zzrCFEtwwD/cvl9PhQhtmyEMKaAvg1517Vflv3XJ+vB6HGU6nyvRmQ2GwECgu+nED4eC4rvlMez0YXLvjl81Gpmq8epkGOGSY+mgDDj68mltw9n35EzNPIZ94v07AJ5aYs+jka7PBxpReaPymhqklrg+2HA3WYAysnojzOqEqvYhTndaqwvmPhH4cb3OqOkpG2Qd/BtLo66LH6UedRXa0EsagJa3+R8FWY9G49GGlxoTCrYboDNDfP71WinzVpeuMZ8RjlouY7+qa+7BaCStQ5GGlmwFplPqKpBy82iZOBBAS5vuidae1//YLei5egGzAYvDhrTn375oMUDm4WKJvIz7lBFzvOzTIbjzfq2LQpZoyMG3SO7qngxEbCkXZ/2kkK/mPBROkPyA/f2UPltZ7qNiJffcMttTMSH436ax5vpSJG00rFcMMaAuTp4W9TDEolG/I10qGKumLEzUC1/RCPb3mHKHcTnnf5cDf12+Wy7XTBBwyeNkQAOoR4t3vJTsvqPmzB61PopOpTt/Y/3zJm78ahKCbFr6YZvDMHAbr+UkypSyshm84/p9xOINNGUJPsPPE9fVFOiFEhpQ0qmoTcaGO0Ij3Jc8lOCMEbBCrKNtztFwv6BQ7S9FYHCxsk4Hi5UulLrS8keJ9riXLewDGFStXzg506pDSYSk6iuzrQ1bHQkstScZsB5ADaTWkBJfADzHqU
  template:
    metadata:
      name: redis-password
      namespace: budget-tracker
