apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-token
  namespace: budget-tracker
spec:
  encryptedData:
    token: AgBM3JXLjOBD8oNzRYEcYHYQvdH3Ozf6DHaMe1lU/Nn9wqNQUGexCNQkK6oZpezfwGsGmPJVbQE0cxtVqEwYUyJYrkj7i9gsqa99x7tHZRm/SPSgOSbr/aJ/F5d6wXBHsU7hjIFVPyjRQDm3mi9/f9qi9N4r0Z1nZ+LqUGIXc5dbAKw4HoCgGU/snf7QYDWkJwtsQSqDOXbYyxyh3o1vO7aC7jIL71uxNqNCIbVO269zK3d/yaAcHkFqCgJV1qPSTamrN+AUf6zxR0Gdf6fld8cVZcBXNcJPEchLWUJfn+ZSvc8VsiMoGYNqpypX7l9oen3fcGOguhn7aa6Kbk1RSMn/z7J2mUvXRocYpgakzkq0pUTnTkCF6DbvHbCyDb4d7MO58b/TO8uG6HtzmwHX/iUnYiaD1UcETedU5jFO41Q6L7WCoP57AUlEodC34AY8zKG2vlHWBoovnbq7s8K4anWFg435Fuo+zAWP3kP3MuLW3RjwQbdmga0OZvrEJkFOx64aYezxIECtqOXAmKsImiaB1ddO7CZkJRG0V+LS/HPiSf9I1IzViF/0YhvxqHwNZS2ib9SNtgc1zokejY6b9ENnnk6djvjDOxKgdKJyUf5619/Y+pU3m+vr7W0Vkh6O15BpoHg2SE3W7xYNMrmKnGQZn6gqGxPa7dqUvtBB4ceAHKP+pQfGyrmA6IdjAZdOMdlxwoEVH2yxgT+YC86Phnziec/OvtXFHWjKCYaJDUBIcsI4peY5sIwkPvLu
  template:
    metadata:
      name: jwt-token
      namespace: budget-tracker
